services:
  wordpress:
    build: .
    container_name: wordpress-app-prod
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DEBUG: "1"
      WORDPRESS_DEBUG_LOG: "1"
      WORDPRESS_DEBUG_DISPLAY: "1"
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d:/usr/local/etc/php/conf.d"
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - wordpress_data:/var/www/html

volumes:
  wordpress_data:

