services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_proxy_certs:/etc/nginx/certs:ro
      - nginx_proxy_vhost:/etc/nginx/vhost.d
      - nginx_proxy_html:/usr/share/nginx/html
    labels:
      - "com.github.nginx-proxy.nginx-proxy"

  letsencrypt:
    image: nginxproxy/acme-companion:latest
    container_name: letsencrypt
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_proxy_certs:/etc/nginx/certs:rw
      - nginx_proxy_vhost:/etc/nginx/vhost.d
      - nginx_proxy_html:/usr/share/nginx/html
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL:-admin@example.com}
    depends_on:
      - nginx-proxy

  wordpress:
    build: .
    container_name: wordpress-app-prod
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_HOST:-192.168.0.4}:${MYSQL_PORT:-3306}
      WORDPRESS_DB_NAME: ${MYSQL_DBNAME:-default_db}
      WORDPRESS_DB_USER: ${MYSQL_USER:-gen_user}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD:-sv4Y>9DO8:fL&N}
      WORDPRESS_DEBUG: "1"
      WORDPRESS_DEBUG_LOG: "1"
      WORDPRESS_DEBUG_DISPLAY: "1"
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d:/usr/local/etc/php/conf.d"
      VIRTUAL_HOST: ${DOMAIN_NAME}
      LETSENCRYPT_HOST: ${DOMAIN_NAME}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-admin@example.com}
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - wordpress_data:/var/www/html
    depends_on:
      - nginx-proxy
      - letsencrypt

volumes:
  wordpress_data:
  nginx_proxy_certs:
  nginx_proxy_vhost:
  nginx_proxy_html:

